// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjqBHlBRhxUYpMq92kfMk8zsxzW7xFDcY',
    appId: '1:898695960774:web:a7a21c5caf34fabb331fc7',
    messagingSenderId: '898695960774',
    projectId: 'campusgo-6eec2',
    authDomain: 'campusgo-6eec2.firebaseapp.com',
    storageBucket: 'campusgo-6eec2.appspot.com',
    measurementId: 'G-Q574GCHY2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ANzijiyhjQI4Ds1wHDlCOrmZGXsueZ8',
    appId: '1:898695960774:android:3662bfd2b26c45bb331fc7',
    messagingSenderId: '898695960774',
    projectId: 'campusgo-6eec2',
    storageBucket: 'campusgo-6eec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJZdNdbQV4VmnTOh8ya8o1cAfdvaaIy54',
    appId: '1:898695960774:ios:27a2b83c6b0c41de331fc7',
    messagingSenderId: '898695960774',
    projectId: 'campusgo-6eec2',
    storageBucket: 'campusgo-6eec2.appspot.com',
    iosClientId: '898695960774-8p0oth105le9g78ta7p0qsfn3asfmfd6.apps.googleusercontent.com',
    iosBundleId: 'com.examplecampusgo.campusgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJZdNdbQV4VmnTOh8ya8o1cAfdvaaIy54',
    appId: '1:898695960774:ios:27a2b83c6b0c41de331fc7',
    messagingSenderId: '898695960774',
    projectId: 'campusgo-6eec2',
    storageBucket: 'campusgo-6eec2.appspot.com',
    iosClientId: '898695960774-8p0oth105le9g78ta7p0qsfn3asfmfd6.apps.googleusercontent.com',
    iosBundleId: 'com.examplecampusgo.campusgo',
  );
}
